
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 10 00:48:44 CDT 2018
//----------------------------------------------------

package mx.com.mont.automat;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IMPORT = 14;
  public static final int PUNTO = 24;
  public static final int VALI = 2;
  public static final int VALF = 3;
  public static final int FIN_LINEA = 17;
  public static final int VALC = 4;
  public static final int SUMA = 7;
  public static final int DIVI = 6;
  public static final int RETURN = 15;
  public static final int NUMI = 25;
  public static final int NUMF = 26;
  public static final int ID = 27;
  public static final int COM_SIMPLE = 18;
  public static final int COMA = 22;
  public static final int ASIGNACION = 19;
  public static final int SYM = 23;
  public static final int EOF = 0;
  public static final int MULT = 9;
  public static final int SALIDA = 20;
  public static final int MAIN = 16;
  public static final int PAR_IZQ = 12;
  public static final int error = 1;
  public static final int ENTRADA = 21;
  public static final int PAR_DER = 13;
  public static final int COR_IZQ = 10;
  public static final int COR_DER = 11;
  public static final int VALS = 5;
  public static final int RESTA = 8;
}

